name: simple_flashcard
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  auto_route: ^8.0.3
  bloc: ^8.1.4
  drift: ^2.16.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  intl: ^0.19.0
  path: ^1.9.0
  path_provider: ^2.1.2
  percent_indicator: ^4.2.3
  sqlite3_flutter_libs: ^0.5.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  drift_dev: ^2.16.0
  build_runner: ^2.4.9
  auto_route_generator: ^8.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/profile.png
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
